# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 780, 500))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_server = QtWidgets.QWidget()
        self.tab_server.setObjectName("tab_server")
        self.btnLoadCSRs = QtWidgets.QPushButton(self.tab_server)
        self.btnLoadCSRs.setGeometry(QtCore.QRect(10, 10, 180, 30))
        self.btnLoadCSRs.setObjectName("btnLoadCSRs")
        self.btnSignSelected = QtWidgets.QPushButton(self.tab_server)
        self.btnSignSelected.setGeometry(QtCore.QRect(200, 10, 180, 30))
        self.btnSignSelected.setObjectName("btnSignSelected")
        self.tableCSRs = QtWidgets.QTableWidget(self.tab_server)
        self.tableCSRs.setGeometry(QtCore.QRect(10, 50, 740, 400))
        self.tableCSRs.setObjectName("tableCSRs")
        self.tableCSRs.setColumnCount(0)
        self.tableCSRs.setRowCount(0)
        self.btnExportCert = QtWidgets.QPushButton(self.tableCSRs)
        self.btnExportCert.setGeometry(QtCore.QRect(10, 460, 160, 30))
        self.btnExportCert.setObjectName("btnExportCert")
        self.btnRevoke = QtWidgets.QPushButton(self.tableCSRs)
        self.btnRevoke.setGeometry(QtCore.QRect(180, 460, 100, 30))
        self.btnRevoke.setObjectName("btnRevoke")
        self.btnExportAll = QtWidgets.QPushButton(self.tableCSRs)
        self.btnExportAll.setGeometry(QtCore.QRect(400, 460, 150, 30))
        self.btnExportAll.setObjectName("btnExportAll")
        self.btnUnrevoke = QtWidgets.QPushButton(self.tableCSRs)
        self.btnUnrevoke.setGeometry(QtCore.QRect(290, 460, 100, 30))
        self.btnUnrevoke.setObjectName("btnUnrevoke")
        self.tabWidget.addTab(self.tab_server, "")
        self.tab_clients = QtWidgets.QWidget()
        self.tab_clients.setObjectName("tab_clients")
        self.searchInput = QtWidgets.QLineEdit(self.tab_clients)
        self.searchInput.setGeometry(QtCore.QRect(10, 10, 400, 25))
        self.searchInput.setObjectName("searchInput")
        self.tableClients = QtWidgets.QTableWidget(self.tab_clients)
        self.tableClients.setGeometry(QtCore.QRect(10, 10, 740, 440))
        self.tableClients.setObjectName("tableClients")
        self.tableClients.setColumnCount(0)
        self.tableClients.setRowCount(0)
        self.btnExportCert1 = QtWidgets.QPushButton(self.tableClients)
        self.btnExportCert1.setGeometry(QtCore.QRect(10, 460, 160, 30))
        self.btnExportCert1.setObjectName("btnExportCert1")
        self.btnRevoke1 = QtWidgets.QPushButton(self.tableClients)
        self.btnRevoke1.setGeometry(QtCore.QRect(180, 460, 100, 30))
        self.btnRevoke1.setObjectName("btnRevoke1")
        self.btnExportAll1 = QtWidgets.QPushButton(self.tableClients)
        self.btnExportAll1.setGeometry(QtCore.QRect(400, 460, 150, 30))
        self.btnExportAll1.setObjectName("btnExportAll1")
        self.btnUnrevoke1 = QtWidgets.QPushButton(self.tableClients)
        self.btnUnrevoke1.setGeometry(QtCore.QRect(290, 460, 100, 30))
        self.btnUnrevoke1.setObjectName("btnUnrevoke1")
        self.tabWidget.addTab(self.tab_clients, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SSL-Zertifikatsverwaltung"))
        self.btnLoadCSRs.setText(_translate("MainWindow", "CSR-Dateien laden"))
        self.btnSignSelected.setText(_translate("MainWindow", "Zertifikat signieren"))
        self.btnExportCert.setText(_translate("MainWindow", "Zertifikat exportieren"))
        self.btnRevoke.setText(_translate("MainWindow", "Sperren"))
        self.btnExportAll.setText(_translate("MainWindow", "Daten exportieren"))
        self.btnUnrevoke.setText(_translate("MainWindow", "Freigeben"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_server), _translate("MainWindow", "CA / Server"))
        self.searchInput.setPlaceholderText(_translate("MainWindow", "Client-Name suchen..."))
        self.btnExportCert1.setText(_translate("MainWindow", "Zertifikat exportieren"))
        self.btnRevoke1.setText(_translate("MainWindow", "Sperren"))
        self.btnExportAll1.setText(_translate("MainWindow", "Daten exportieren"))
        self.btnUnrevoke1.setText(_translate("MainWindow", "Freigeben"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_clients), _translate("MainWindow", "Clients"))
