name: Compile UI and Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src\CertTool\exports\requirements.txt

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile src\CertTool\exports\main.py

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: CertTool_Export_Windows
        path: dist/*.exe

    - name: Upload Windows Release
      uses: actions/upload-artifact@v4
      with:
          files: |
            LICENSE
            dist/main.exe

  build-macos:
    runs-on: macos-latest
    name: Build on macOS
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r src/CertTool/exports/requirements.txt
          pip install pyinstaller

      - name: Build APP with PyInstaller
        run: pyinstaller --noconfirm --onefile src/CertTool/exports/main.py

      - name: Upload macOS build
        uses: actions/upload-artifact@v4
        with:
          name: Mac OS Application
          path: dist/**

          
