name: Compile UI and Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src\CertTool\exports\requirements.txt

    - name: Compile .ui files to .py
      run: |
        mkdir -p src\CertTool\exports\ui
        for %%f in (src\CertTool\exports\*.ui) do (
          pyuic5 -o src\CertTool\exports\ui\ui_%%~nf.py src\CertTool\exports\%%~nxf
        )

    - name: Build EXE
      run: |
        pyinstaller --noconfirm --onefile src\CertTool\exports\main.py

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: CertTool_Export_Windows
        path: dist/*.exe
